name: bookly_app_with_mvvm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  dio: ^5.4.2+1
  flutter_bloc: ^8.1.5
  get_it: ^7.6.8
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.2



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/
     - assets/json/



  fonts:
     - family: GTFont
       fonts:
         - asset: assets/fonts/GT Sectra Fine Regular.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
